// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: mpsv.proto

// protoc --go_out=plugins=grpc:. *.proto

package mpsv

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MpsvUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *MpsvUrl) Reset() {
	*x = MpsvUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mpsv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MpsvUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpsvUrl) ProtoMessage() {}

func (x *MpsvUrl) ProtoReflect() protoreflect.Message {
	mi := &file_mpsv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpsvUrl.ProtoReflect.Descriptor instead.
func (*MpsvUrl) Descriptor() ([]byte, []int) {
	return file_mpsv_proto_rawDescGZIP(), []int{0}
}

func (x *MpsvUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MpsvOffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MpsvId  string `protobuf:"bytes,1,opt,name=mpsvId,proto3" json:"mpsvId,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *MpsvOffer) Reset() {
	*x = MpsvOffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mpsv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MpsvOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpsvOffer) ProtoMessage() {}

func (x *MpsvOffer) ProtoReflect() protoreflect.Message {
	mi := &file_mpsv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpsvOffer.ProtoReflect.Descriptor instead.
func (*MpsvOffer) Descriptor() ([]byte, []int) {
	return file_mpsv_proto_rawDescGZIP(), []int{1}
}

func (x *MpsvOffer) GetMpsvId() string {
	if x != nil {
		return x.MpsvId
	}
	return ""
}

func (x *MpsvOffer) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MpsvOffer) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_mpsv_proto protoreflect.FileDescriptor

var file_mpsv_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x70, 0x73, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x22, 0x1b, 0x0a, 0x07, 0x4d, 0x70, 0x73, 0x76, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22,
	0x53, 0x0a, 0x09, 0x4d, 0x70, 0x73, 0x76, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x70, 0x73, 0x76, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x70,
	0x73, 0x76, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x32, 0x40, 0x0a, 0x0a, 0x4d, 0x70, 0x73, 0x76, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x72, 0x12, 0x32, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x73, 0x65, 0x4d, 0x70, 0x73, 0x76, 0x55,
	0x72, 0x6c, 0x12, 0x0d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4d, 0x70, 0x73, 0x76, 0x55, 0x72,
	0x6c, 0x1a, 0x0f, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4d, 0x70, 0x73, 0x76, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x22, 0x00, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mpsv_proto_rawDescOnce sync.Once
	file_mpsv_proto_rawDescData = file_mpsv_proto_rawDesc
)

func file_mpsv_proto_rawDescGZIP() []byte {
	file_mpsv_proto_rawDescOnce.Do(func() {
		file_mpsv_proto_rawDescData = protoimpl.X.CompressGZIP(file_mpsv_proto_rawDescData)
	})
	return file_mpsv_proto_rawDescData
}

var file_mpsv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mpsv_proto_goTypes = []interface{}{
	(*MpsvUrl)(nil),   // 0: auth.MpsvUrl
	(*MpsvOffer)(nil), // 1: auth.MpsvOffer
}
var file_mpsv_proto_depIdxs = []int32{
	0, // 0: auth.MpsvParser.ParseMpsvUrl:input_type -> auth.MpsvUrl
	1, // 1: auth.MpsvParser.ParseMpsvUrl:output_type -> auth.MpsvOffer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mpsv_proto_init() }
func file_mpsv_proto_init() {
	if File_mpsv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mpsv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MpsvUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpsv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MpsvOffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mpsv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mpsv_proto_goTypes,
		DependencyIndexes: file_mpsv_proto_depIdxs,
		MessageInfos:      file_mpsv_proto_msgTypes,
	}.Build()
	File_mpsv_proto = out.File
	file_mpsv_proto_rawDesc = nil
	file_mpsv_proto_goTypes = nil
	file_mpsv_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MpsvParserClient is the client API for MpsvParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MpsvParserClient interface {
	ParseMpsvUrl(ctx context.Context, in *MpsvUrl, opts ...grpc.CallOption) (MpsvParser_ParseMpsvUrlClient, error)
}

type mpsvParserClient struct {
	cc grpc.ClientConnInterface
}

func NewMpsvParserClient(cc grpc.ClientConnInterface) MpsvParserClient {
	return &mpsvParserClient{cc}
}

func (c *mpsvParserClient) ParseMpsvUrl(ctx context.Context, in *MpsvUrl, opts ...grpc.CallOption) (MpsvParser_ParseMpsvUrlClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MpsvParser_serviceDesc.Streams[0], "/auth.MpsvParser/ParseMpsvUrl", opts...)
	if err != nil {
		return nil, err
	}
	x := &mpsvParserParseMpsvUrlClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MpsvParser_ParseMpsvUrlClient interface {
	Recv() (*MpsvOffer, error)
	grpc.ClientStream
}

type mpsvParserParseMpsvUrlClient struct {
	grpc.ClientStream
}

func (x *mpsvParserParseMpsvUrlClient) Recv() (*MpsvOffer, error) {
	m := new(MpsvOffer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MpsvParserServer is the server API for MpsvParser service.
type MpsvParserServer interface {
	ParseMpsvUrl(*MpsvUrl, MpsvParser_ParseMpsvUrlServer) error
}

// UnimplementedMpsvParserServer can be embedded to have forward compatible implementations.
type UnimplementedMpsvParserServer struct {
}

func (*UnimplementedMpsvParserServer) ParseMpsvUrl(*MpsvUrl, MpsvParser_ParseMpsvUrlServer) error {
	return status.Errorf(codes.Unimplemented, "method ParseMpsvUrl not implemented")
}

func RegisterMpsvParserServer(s *grpc.Server, srv MpsvParserServer) {
	s.RegisterService(&_MpsvParser_serviceDesc, srv)
}

func _MpsvParser_ParseMpsvUrl_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MpsvUrl)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MpsvParserServer).ParseMpsvUrl(m, &mpsvParserParseMpsvUrlServer{stream})
}

type MpsvParser_ParseMpsvUrlServer interface {
	Send(*MpsvOffer) error
	grpc.ServerStream
}

type mpsvParserParseMpsvUrlServer struct {
	grpc.ServerStream
}

func (x *mpsvParserParseMpsvUrlServer) Send(m *MpsvOffer) error {
	return x.ServerStream.SendMsg(m)
}

var _MpsvParser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.MpsvParser",
	HandlerType: (*MpsvParserServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ParseMpsvUrl",
			Handler:       _MpsvParser_ParseMpsvUrl_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mpsv.proto",
}
